# Generated by Django 3.2.9 on 2021-11-11 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api_dog_manager', '0001_initial'),
        ('api_login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='walker',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_login.person', to_field='user_id'),
        ),
        migrations.AddField(
            model_name='eventcalendar',
            name='walker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_dog_manager.walker'),
        ),
        migrations.AddField(
            model_name='dogs',
            name='dogsize',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api_dog_manager.dogsize'),
        ),
        migrations.AddField(
            model_name='dogs',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_login.person'),
        ),
    ]
